import { LotteryResult, NewsPost, Banner } from '../types';

export const INITIAL_BANNERS: Banner[] = [
  {
    id: 'b1',
    titleEN: 'Official Lottery Portal',
    titleTH: 'พอร์ทัลสลากกินแบ่งรัฐบาลอย่างเป็นทางการ',
    titleBN: 'অফিসিয়াল লটারি পোর্টাল',
    subtitleEN: 'Check Results Instantly & Secure Your Tickets Online',
    subtitleTH: 'ตรวจผลรางวัลทันทีและซื้อสลากออนไลน์อย่างปลอดภัย',
    subtitleBN: 'সহজেই ফলাফল যাচাই করুন এবং অনলাইনে টিকিট সংগ্রহ করুন',
    imageUrl: 'https://images.unsplash.com/photo-1518546305927-5a555bb7020d?q=80&w=1200&auto=format&fit=crop',
    link: '#checker'
  },
  {
    id: 'b2',
    titleEN: 'Grand Prize Draw #105',
    titleTH: 'การออกรางวัลครั้งใหญ่ งวดที่ 105',
    titleBN: 'মেগা ড্র #১০৫',
    subtitleEN: 'Next Draw on July 16, 2026. Jackpot starts at 6,000,000 ฿',
    subtitleTH: 'ออกรางวัลถัดไปวันที่ 16 กรกฎาคม 2569 รางวัลที่ 1 มูลค่า 6,000,000 บาท',
    subtitleBN: 'পরবর্তী ড্র ১৬ জুলাই, ২০২৬। প্রথম পুরস্কার ৬,০০০,০০০ ฿',
    imageUrl: 'https://images.unsplash.com/photo-1596838132731-3301c3fd4317?q=80&w=1200&auto=format&fit=crop',
    link: '#checker'
  },
  {
    id: 'b3',
    titleEN: 'Become a Licensed Retailer',
    titleTH: 'สมัครเป็นตัวแทนจำหน่ายสลากดิจิทัล',
    titleBN: 'লাইসেন্সড রিটেইলার হন',
    subtitleEN: 'Join our government digital ecosystem and grow your business safely',
    subtitleTH: 'เข้าร่วมระบบนิเวศดิจิทัลของรัฐบาลและขยายธุรกิจของคุณอย่างปลอดภัย',
    subtitleBN: 'সরকারি ডিজিটাল প্ল্যাটফর্মে যোগ দিন এবং আপনার ব্যবসা বৃদ্ধি করুন',
    imageUrl: 'https://images.unsplash.com/photo-1526304640581-d334cdbbf45e?q=80&w=1200&auto=format&fit=crop',
    link: '#contact'
  }
];

export const INITIAL_LOTTERY_RESULTS: LotteryResult[] = [
  {
    id: 'r1',
    drawDate: '2026-07-01',
    drawNumber: 'Draw #104',
    firstPrize: '123456',
    firstPrizeAmount: 6000000,
    twoDigit: '45',
    threeDigitPrefix: ['123', '456'],
    threeDigitSuffix: ['789', '012'],
    secondPrize: ['234567', '345678', '456789', '567890', '678901'],
    thirdPrize: ['112233', '223344', '334455', '445566', '556677', '667788', '778899', '889900', '990011', '121212'],
    status: 'Drawn'
  },
  {
    id: 'r2',
    drawDate: '2026-06-16',
    drawNumber: 'Draw #103',
    firstPrize: '782390',
    firstPrizeAmount: 6000000,
    twoDigit: '12',
    threeDigitPrefix: ['901', '342'],
    threeDigitSuffix: ['556', '891'],
    secondPrize: ['881122', '341256', '772189', '904512', '128956'],
    thirdPrize: ['111111', '222222', '333333', '444444', '555555', '666666', '777777', '888888', '999999', '000000'],
    status: 'Drawn'
  },
  {
    id: 'r3',
    drawDate: '2026-06-01',
    drawNumber: 'Draw #102',
    firstPrize: '561902',
    firstPrizeAmount: 6000000,
    twoDigit: '89',
    threeDigitPrefix: ['451', '230'],
    threeDigitSuffix: ['678', '912'],
    secondPrize: ['120934', '568901', '347890', '219087', '764512'],
    thirdPrize: ['561102', '190256', '230451', '912678', '442190', '123123', '456456', '789789', '112211', '334433'],
    status: 'Drawn'
  },
  {
    id: 'r4',
    drawDate: '2026-05-16',
    drawNumber: 'Draw #101',
    firstPrize: '098765',
    firstPrizeAmount: 6000000,
    twoDigit: '23',
    threeDigitPrefix: ['112', '334'],
    threeDigitSuffix: ['556', '778'],
    secondPrize: ['987654', '876543', '765432', '654321', '543210'],
    thirdPrize: ['123456', '234567', '345678', '456789', '567890', '678901', '789012', '890123', '901234', '012345'],
    status: 'Drawn'
  },
  {
    id: 'r5',
    drawDate: '2026-07-16',
    drawNumber: 'Draw #105',
    firstPrize: '??????',
    firstPrizeAmount: 6000000,
    twoDigit: '??',
    threeDigitPrefix: ['???', '???'],
    threeDigitSuffix: ['???', '???'],
    secondPrize: [],
    thirdPrize: [],
    status: 'Upcoming'
  }
];

export const INITIAL_NEWS: NewsPost[] = [
  {
    id: 'n1',
    titleEN: 'Thailand Lottery Digital App Expands Retail Operations',
    titleTH: 'แอปสลากดิจิทัลขยายฐานผู้ขายออนไลน์ทั่วประเทศ',
    titleBN: 'ডিজিটাল লটারি অ্যাপে রিটেইল কার্যক্রম সম্প্রসারণ',
    summaryEN: 'The Government Lottery Office announces an expansion of digital vendors to empower micro-sellers across the country.',
    summaryTH: 'สำนักงานสลากกินแบ่งรัฐบาลประกาศขยายโควตาตัวแทนจำหน่ายสลากดิจิทัล เพื่อส่งเสริมรายย่อยและลดการจำหน่ายเกินราคา',
    summaryBN: 'ক্ষুদ্র বিক্রেতাদের স্বাবলম্বী করতে সরকারি ডিজিটাল লটারি ডিলারশিপের পরিধি বাড়ানো হচ্ছে।',
    contentEN: 'The Government Lottery Office (GLO) has officially announced an expansion in its digital ticket platform. In an effort to keep ticket prices strictly at 80 Baht, the GLO is increasing the pool of licensed digital retailers. This move aims to allow thousands of disabled and micro-retailers to sell tickets directly via our secure secure digital portal, bringing convenience and safety to both buyers and sellers alike.',
    contentTH: 'สำนักงานสลากกินแบ่งรัฐบาล (GLO) ประกาศขยายโควตาผู้ค้าสลากดิจิทัลเพื่อช่วยรักษาราคาจำหน่ายสลากกินแบ่งรัฐบาลให้อยู่ในเกณฑ์ 80 บาทตามกฎหมาย นอกจากนี้ยังเปิดโอกาสให้ผู้พิการและกลุ่มผู้ค้าสลากรายย่อยเข้าสู่ระบบสลากดิจิทัลผ่านแอปพลิเคชันอย่างเป็นทางการมากขึ้นเพื่อความปลอดภัย โปร่งใส และลดการเอารัดเอาเปรียบผู้บริโภค',
    contentBN: 'সরকারি লটারি অফিস (GLO) আনুষ্ঠানিকভাবে ডিজিটাল টিকিট প্ল্যাটফর্মের সম্প্রসারণ ঘোষণা করেছে। লটারির টিকিট মূল্য কঠোরভাবে ৮০ বাথ-এ রাখতে, লাইসেন্সপ্রাপ্ত ডিজিটাল ডিলারের সংখ্যা বৃদ্ধি করা হচ্ছে। এর ফলে হাজার হাজার প্রতিবন্ধী ও ক্ষুদ্র বিক্রেতা আমাদের সুরক্ষিত পোর্টালের মাধ্যমে সরাসরি টিকিট বিক্রি করতে পারবেন, যা ক্রেতা এবং বিক্রেতা উভয়ের জন্য সুবিধা ও নিরাপত্তা নিশ্চিত করবে।',
    date: '2026-06-28',
    imageUrl: 'https://images.unsplash.com/photo-1542838132-92c53300491e?q=80&w=600&auto=format&fit=crop'
  },
  {
    id: 'n2',
    titleEN: 'Security Warning: Always Buy from Authorized Channels Only',
    titleTH: 'คำเตือนความปลอดภัย: โปรดซื้อสลากจากช่องทางที่ได้รับอนุมัติเท่านั้น',
    titleBN: 'নিরাপত্তা সতর্কবার্তা: শুধুমাত্র অনুমোদিত উৎস থেকে টিকিট কিনুন',
    summaryEN: 'Ensure your ticket authenticity by purchasing only through the official digital platform or registered physical retailers.',
    summaryTH: 'กรุณาตรวจสอบความถูกต้องและซื้อสลากผ่านระบบออนไลน์อย่างเป็นทางการ หรือร้านค้าจีแอลโอที่มีตราสัญลักษณ์ที่ถูกต้อง',
    summaryBN: 'আপনার টিকিটের সত্যতা নিশ্চিত করতে শুধুমাত্র অফিসিয়াল ডিজিটাল অ্যাপ অথবা নিবন্ধিত খুচরা বিক্রেতাদের কাছ থেকে ক্রয় করুন।',
    contentEN: 'Due to a rise in counterfeit tickets and online scams claiming to sell guaranteed winning numbers, the Government Lottery Office urges the public to remain vigilant. Authentic digital tickets can only be purchased and managed through the verified Government Portal. Winning payments are processed automatically to registered bank accounts, eliminating the risk of fraud.',
    contentTH: 'สืบเนื่องจากกรณีการตรวจพบสลากปลอมและกลุ่มมิจฉาชีพที่อ้างอิงสูตรเลขล็อคหรือรับซื้อสลากในราคาเกินจริง สำนักงานสลากกินแบ่งรัฐบาลขอแจ้งเตือนให้ประชาชนซื้อสลากจากแอปพลิเคชันทางการเท่านั้น โดยผู้ถูกรางวัลสามารถขึ้นรางวัลด้วยความปลอดภัยผ่านการโอนตรงเข้าบัญชีธนาคารเท่านั้น ไม่มีการเรียกเก็บค่าธรรมเนียมล่วงหน้า',
    contentBN: 'জাল টিকিট এবং লটারি জয়ের মিথ্যা আশ্বাসের ঘটনা বৃদ্ধি পাওয়ায় সরকারি লটারি অফিস জনগণকে সতর্ক থাকার পরামর্শ দিচ্ছে। খাঁটি ডিজিটাল টিকিট শুধুমাত্র আমাদের ভেরিফাইড পোর্টালের মাধ্যমে কেনা এবং পরিচালনা করা যায়। বিজয়ী টিকিটগুলোর পুরস্কার সরাসরি ব্যাংক অ্যাকাউন্টে পাঠিয়ে দেওয়া হয়, ফলে প্রতারণার কোনো সুযোগ নেই।',
    date: '2026-06-15',
    imageUrl: 'https://images.unsplash.com/photo-1563013544-824ae1d704d3?q=80&w=600&auto=format&fit=crop'
  }
];

export const FAQS = [
  {
    id: 'faq1',
    qEN: 'How do I check my lottery results on this portal?',
    qTH: 'ฉันจะตรวจผลรางวัลสลากกินแบ่งได้อย่างไร?',
    qBN: 'আমি কীভাবে এই পোর্টালে আমার লটারির ফলাফল চেক করব?',
    aEN: 'You can check your ticket instantly by typing your 6-digit number and selecting the draw date in our Lottery Result Checker section. The system will automatically display your prize rank, status, and winning amounts.',
    aTH: 'คุณสามารถตรวจผลรางวัลได้ทันทีโดยการกรอกหมายเลขสลาก 6 หลัก และเลือกงวดวันที่ออกรางวัลในส่วนของเครื่องมือตรวจสลาก ระบบจะแสดงรางวัลที่คุณได้รับ สถานะ และจำนวนเงินรางวัลโดยอัตโนมัติ',
    aBN: 'আমাদের লটারি রেজাল্ট চেকার সেকশনে আপনার ৬-ডিজিটের টিকিট নম্বর এবং ড্র-এর তারিখ নির্বাচন করে খুব সহজেই আপনার টিকিট চেক করতে পারেন। সিস্টেমটি স্বয়ংক্রিয়ভাবে আপনার বিজয়ী র‍্যাঙ্ক এবং পুরস্কারের পরিমাণ প্রদর্শন করবে।'
  },
  {
    id: 'faq2',
    qEN: 'How are prizes distributed to winners?',
    qTH: 'ผู้ถูกรางวัลจะได้รับเงินรางวัลอย่างไร?',
    qBN: 'বিজয়ীদের কীভাবে পুরস্কারের টাকা দেওয়া হয়?',
    aEN: 'For digital ticket holders, winning amounts are credited directly to your saved bank account or digital wallet within 24 hours. For physical ticket holders, you can claim your prize at the nearest government branch or authorized banks.',
    aTH: 'สำหรับผู้ถือสลากดิจิทัล เงินรางวัลจะถูกโอนเข้าบัญชีธนาคารหรือกระเป๋าเงินดิจิทัลที่ลงทะเบียนไว้ภายใน 24 ชั่วโมง สำหรับผู้ถือสลากใบ สามารถขึ้นเงินได้ที่สำนักงานสลากกินแบ่งรัฐบาล หรือธนาคารที่ได้รับอนุญาต',
    aBN: 'ডিজিটাল টিকিটধারীদের ক্ষেত্রে, বিজয়ী অর্থ ২৪ ঘণ্টার মধ্যে সরাসরি আপনার সংরক্ষিত ব্যাংক অ্যাকাউন্ট অথবা ডিজিটাল ওয়ালেটে জমা হয়ে যায়। কাগজের টিকিটধারীরা নিকটস্থ সরকারি শাখা বা অনুমোদিত ব্যাংক থেকে পুরস্কার দাবি করতে পারেন।'
  },
  {
    id: 'faq3',
    qEN: 'What payment methods are supported for online ticket buying?',
    qTH: 'รองรับช่องทางการชำระเงินใดบ้างสำหรับการซื้อสลากออนไลน์?',
    qBN: 'অনলাইনে টিকিট কেনার জন্য কী কী পেমেন্ট পদ্ধতি ব্যবহার করা যাবে?',
    aEN: 'We support a variety of secure simulated payment methods: Credit/Debit Cards, QR Code Payments (PromptPay / TrueMoney in Thailand, and bKash / Nagad in Bangladesh) for user convenience.',
    aTH: 'เรารองรับช่องทางการชำระเงินที่ปลอดภัยที่หลากหลาย: บัตรเครดิต/เดบิต, สแกนคิวอาร์โค้ด (PromptPay / TrueMoney) รวมถึงช่องทางชำระเงินผ่านมือถือยอดนิยมอย่าง bKash และ Nagad เพื่อความสะดวกสูงสุด',
    aBN: 'আমরা বিভিন্ন নিরাপদ পেমেন্ট পদ্ধতি সমর্থন করি: ক্রেডিট/ডেবিট কার্ড, কিউআর কোড পেমেন্ট (থাইল্যান্ডের প্রম্পটপে/ট্রুমানি এবং বাংলাদেশের বিকাশ ও নগদ) ব্যবহার করে খুব সহজে পেমেন্ট করা যাবে।'
  }
];

export const DICTIONARY: Record<string, Record<string, string>> = {
  EN: {
    appName: 'Global Lottery Portal',
    navHome: 'Home',
    navResults: 'Results',
    navNews: 'News',
    navServices: 'Services',
    navContact: 'Contact',
    btnSearch: 'Search',
    btnLogin: 'Login',
    btnRegister: 'Register',
    btnDashboard: 'Dashboard',
    btnAdmin: 'Admin Panel',
    btnLogout: 'Logout',
    govHeader: 'Government Lottery Office Portal',
    announcement: 'Alert:',
    alertNotice: 'Draw #105 starts in 2 hours! Live stream starts at 14:00 GMT+7.',
    heroCtaCheck: 'Check Result',
    heroCtaBuy: 'Buy Tickets',
    quickCheck: 'Check Lottery',
    quickBuy: 'Buy Ticket',
    quickWinners: 'Winners',
    quickStats: 'Statistics',
    quickFaq: 'FAQ',
    quickContact: 'Contact Us',
    checkerTitle: 'Official Ticket Result Checker',
    checkerSubtitle: 'Enter your 6-digit ticket number to check winning status.',
    lblTicketNo: 'Ticket Number (6 digits)',
    lblDrawDate: 'Select Draw Date',
    btnCheckNow: 'Check Winning Status',
    lblWinnersShowcase: 'Winner Showcase',
    lblWinnersSubtitle: 'Congratulations to our latest multi-millionaire winners!',
    lblStatsTitle: 'Portal Performance & Statistics',
    lblStatsSubtitle: 'Real-time indicators of our secure lottery ecosystem.',
    statTicketsSold: 'Total Tickets Sold',
    statTotalWinners: 'Total Winners Awarded',
    statPrizesPaid: 'Prize Distributed (฿)',
    statActiveUsers: 'Active Digital Users',
    lblDownloadApp: 'Download Our Official App',
    lblDownloadSubtitle: 'Access instant drawings, secure tickets, and alerts on your mobile device.',
    lblFaqTitle: 'Frequently Asked Questions (FAQ)',
    lblFaqSubtitle: 'Everything you need to know about purchasing, claiming, and safety.',
    lblFooterRights: 'All Rights Reserved. Official Government Lottery Office Portal © 2026.',
    lblFooterAddress: '44 Ratchadamnoen Avenue, Bangkok, Thailand',
    lblFooterContact: 'Phone: +66 2624 4300 | Email: support@glo.or.th',
    lblLatestDrawTitle: 'Latest Lottery Results',
    lbl1stPrize: '1st Prize',
    lbl2Digit: '2 Digit',
    lbl3DigitPrefix: '3-Digit Prefix',
    lbl3DigitSuffix: '3-Digit Suffix',
    btnDetails: 'View Prize Details',
    drawDate: 'Draw Date',
    amount: 'Prize Amount',
    rank: 'Rank',
    winGreeting: 'CONGRATULATIONS!',
    loseGreeting: 'Better luck next time!',
    winAmountMsg: 'You won a prize of',
    noWinMsg: 'Your ticket has no matching combinations for this draw.',
    verifyMsg: 'Validated by GLO Security Ledger.',
    searchPlaceholder: 'Search tickets, articles, announcements...',
    searchNoResult: 'No matches found.',
    recentSearches: 'Recent Searches',
    savedTickets: 'My Saved Tickets',
    buyTicketTitle: 'Purchase Digital Lottery Ticket',
    chooseDigits: 'Generate / Choose 6 Digits',
    ticketPrice: 'Ticket Price: 80 ฿',
    paymentMethod: 'Choose Payment Gateway',
    btnProceedPayment: 'Simulate Payment',
    paymentSuccess: 'Payment Successful! Ticket added to your dashboard.',
    adminPortal: 'Admin CMS & Operations',
    adminAddResult: 'Upload Drawing Results',
    adminNewsPost: 'Publish New Article',
    adminDraws: 'Drawings list',
    adminTickets: 'Purchased Tickets Log',
    liveCountdown: 'Next Draw Countdown'
  },
  TH: {
    appName: 'พอร์ทัลสลากกินแบ่งรัฐบาล',
    navHome: 'หน้าแรก',
    navResults: 'ผลรางวัล',
    navNews: 'ข่าวสาร',
    navServices: 'บริการ',
    navContact: 'ติดต่อเรา',
    btnSearch: 'ค้นหา',
    btnLogin: 'เข้าสู่ระบบ',
    btnRegister: 'ลงทะเบียน',
    btnDashboard: 'แดชบอร์ด',
    btnAdmin: 'ระบบแอดมิน',
    btnLogout: 'ออกจากระบบ',
    govHeader: 'สำนักงานสลากกินแบ่งรัฐบาล',
    announcement: 'ประกาศ:',
    alertNotice: 'การออกรางวัลครั้งถัดไปจะเริ่มในอีก 2 ชั่วโมง! รับชมการถ่ายทอดสดเวลา 14:00 น.',
    heroCtaCheck: 'ตรวจสลาก',
    heroCtaBuy: 'ซื้อสลากดิจิทัล',
    quickCheck: 'ตรวจผลรางวัล',
    quickBuy: 'ซื้อสลากดิจิทัล',
    quickWinners: 'ทำเนียบผู้โชคดี',
    quickStats: 'สถิติสลาก',
    quickFaq: 'คำถามที่พบบ่อย',
    quickContact: 'ติดต่อสำนักงาน',
    checkerTitle: 'ระบบตรวจผลสลากอย่างเป็นทางการ',
    checkerSubtitle: 'กรอกเลขสลาก 6 หลักของคุณเพื่อตรวจรางวัลแบบเรียลไทม์',
    lblTicketNo: 'เลขสลาก (6 หลัก)',
    lblDrawDate: 'เลือกงวดวันที่ออกรางวัล',
    btnCheckNow: 'ตรวจผลรางวัลทันที',
    lblWinnersShowcase: 'ทำเนียบผู้ถูกรางวัลใหญ่',
    lblWinnersSubtitle: 'ขอแสดงความยินดีกับผู้ถูกรางวัลมหาเศรษฐีทุกท่าน!',
    lblStatsTitle: 'ดัชนีและสถิติการใช้งานระบบ',
    lblStatsSubtitle: 'ตัวบ่งชี้แบบเรียลไทม์สำหรับระบบนิเวศดิจิทัลสลากกินแบ่งรัฐบาล',
    statTicketsSold: 'ยอดจำหน่ายสลากทั้งหมด',
    statTotalWinners: 'จำนวนผู้ถูกรางวัลแล้ว',
    statPrizesPaid: 'จ่ายเงินรางวัลสะสม (บาท)',
    statActiveUsers: 'ผู้ใช้งานระบบดิจิทัล',
    lblDownloadApp: 'ดาวน์โหลดแอปพลิเคชันอย่างเป็นทางการ',
    lblDownloadSubtitle: 'เข้าถึงการออกผลทันใจ ซื้อสลากปลอดภัย และรับแจ้งเตือนทันทีบนมือถือคุณ',
    lblFaqTitle: 'คำถามที่พบบ่อย (FAQ)',
    lblFaqSubtitle: 'ทุกเรื่องน่ารู้เกี่ยวกับการซื้อสลาก การรับเงินรางวัล และมาตรฐานความปลอดภัย',
    lblFooterRights: 'สงวนลิขสิทธิ์ พอร์ทัลสำนักงานสลากกินแบ่งรัฐบาลอย่างเป็นทางการ © 2026',
    lblFooterAddress: '44 ถนนราชดำเนินกลาง แขวงบวรนิเวศ เขตพระนคร กรุงเทพฯ',
    lblFooterContact: 'โทร: +66 2624 4300 | อีเมล: support@glo.or.th',
    lblLatestDrawTitle: 'ผลรางวัลสลากกินแบ่งรัฐบาลล่าสุด',
    lbl1stPrize: 'รางวัลที่ 1',
    lbl2Digit: 'เลขท้าย 2 ตัว',
    lbl3DigitPrefix: 'เลขหน้า 3 ตัว',
    lbl3DigitSuffix: 'เลขท้าย 3 ตัว',
    btnDetails: 'ดูรายละเอียดรางวัล',
    drawDate: 'งวดวันที่',
    amount: 'เงินรางวัล',
    rank: 'รางวัล',
    winGreeting: 'ขอแสดงความยินดีด้วย!',
    loseGreeting: 'ขออภัยด้วย คุณไม่ถูกรางวัลในงวดนี้',
    winAmountMsg: 'คุณถูกรางวัลมูลค่ารวม',
    noWinMsg: 'ไม่พบหมายเลขรางวัลที่ตรงกับสลากของคุณ',
    verifyMsg: 'ตรวจสอบแล้วโดยบัญชีแยกประเภทความปลอดภัย GLO',
    searchPlaceholder: 'ค้นหาสลาก บทความ ประกาศต่างๆ...',
    searchNoResult: 'ไม่พบข้อมูลที่ตรงกัน',
    recentSearches: 'ประวัติการค้นหาล่าสุด',
    savedTickets: 'สลากที่ฉันเซฟไว้',
    buyTicketTitle: 'ซื้อสลากดิจิทัลอย่างปลอดภัย',
    chooseDigits: 'กรอกหรือสุ่มเลข 6 หลัก',
    ticketPrice: 'ราคาใบละ: 80 บาท',
    paymentMethod: 'เลือกช่องทางการชำระเงิน',
    btnProceedPayment: 'ชำระเงินทันที',
    paymentSuccess: 'ชำระเงินสำเร็จ! สลากถูกเพิ่มไปยังแดชบอร์ดของคุณแล้ว',
    adminPortal: 'ระบบการจัดการผู้ดูแลระบบ (Admin CMS)',
    adminAddResult: 'อัปโหลดผลรางวัลสลาก',
    adminNewsPost: 'เขียนข่าวประชาสัมพันธ์ใหม่',
    adminDraws: 'รายการงวดสลากทั้งหมด',
    adminTickets: 'ประวัติการทำรายการซื้อสลากทั้งหมด',
    liveCountdown: 'นับถอยหลังการออกสลากถัดไป'
  },
  BN: {
    appName: 'গ্লোবাল লটারি পোর্টাল',
    navHome: 'হোম',
    navResults: 'ফলাফল',
    navNews: 'খবর',
    navServices: 'সেবাসমূহ',
    navContact: 'যোগাযোগ',
    btnSearch: 'অনুসন্ধান',
    btnLogin: 'লগইন',
    btnRegister: 'নিবন্ধন',
    btnDashboard: 'ড্যাশবোর্ড',
    btnAdmin: 'অ্যাডমিন প্যানেল',
    btnLogout: 'লগআউট',
    govHeader: 'সরকারি লটারি অফিস পোর্টাল',
    announcement: 'ঘোষণা:',
    alertNotice: 'ড্র #১০৫ আর মাত্র ২ ঘন্টার মধ্যে শুরু হচ্ছে! লাইভ সম্প্রচার শুরু হবে দুপুর ১৪:০০ টায়।',
    heroCtaCheck: 'ফলাফল চেক করুন',
    heroCtaBuy: 'টিকিট কিনুন',
    quickCheck: 'লটারি চেক',
    quickBuy: 'টিকিট কিনুন',
    quickWinners: 'বিজয়ী তালিকা',
    quickStats: 'পরিসংখ্যান',
    quickFaq: 'এফএকিউ',
    quickContact: 'যোগাযোগ করুন',
    checkerTitle: 'অফিসিয়াল টিকিট রেজাল্ট চেকার',
    checkerSubtitle: 'আপনার বিজয়ী অবস্থা জানতে ৬-ডিজিটের টিকিট নম্বরটি প্রবেশ করান।',
    lblTicketNo: 'টিকিট নম্বর (৬ ডিজিট)',
    lblDrawDate: 'ড্র-এর তারিখ নির্বাচন করুন',
    btnCheckNow: 'অবস্থা যাচাই করুন',
    lblWinnersShowcase: 'বিজয়ীদের চমৎকার শোকেস',
    lblWinnersSubtitle: 'আমাদের সাম্প্রতিক কোটিপতি লটারি বিজয়ীদের অভিনন্দন!',
    lblStatsTitle: 'পোর্টাল কর্মক্ষমতা ও পরিসংখ্যান',
    lblStatsSubtitle: 'আমাদের সুরক্ষিত লটারি ইকোসিস্টেমের লাইভ সূচক।',
    statTicketsSold: 'মোট টিকিট বিক্রি',
    statTotalWinners: 'মোট পুরস্কৃত বিজয়ী',
    statPrizesPaid: 'বিতরণকৃত পুরস্কার (฿)',
    statActiveUsers: 'সক্রিয় ডিজিটাল ব্যবহারকারী',
    lblDownloadApp: 'আমাদের অফিসিয়াল অ্যাপ ডাউনলোড করুন',
    lblDownloadSubtitle: 'আপনার মোবাইলে সরাসরি ড্র, সুরক্ষিত টিকিট সংরক্ষণ এবং অ্যালার্টের সুবিধা পান।',
    lblFaqTitle: 'সচরাচর জিজ্ঞাস্য (FAQ)',
    lblFaqSubtitle: 'লটারি কেনা, দাবি করা এবং নিরাপত্তা সংক্রান্ত যাবতীয় তথ্য।',
    lblFooterRights: 'সর্বস্বত্ব সংরক্ষিত। অফিসিয়াল সরকারি লটারি অফিস পোর্টাল © ২০২৬।',
    lblFooterAddress: '৪৪ রত্নদামনোয়েন অ্যাভিনিউ, ব্যাংকক, থাইল্যান্ড',
    lblFooterContact: 'ফোন: +৬৬ ২৬২৪ ৪৩০০ | ইমেইল: support@glo.or.th',
    lblLatestDrawTitle: 'সর্বশেষ লটারির ফলাফল',
    lbl1stPrize: '১ম পুরস্কার',
    lbl2Digit: '২ ডিজিট',
    lbl3DigitPrefix: '৩-ডিজিট প্রেফিক্স',
    lbl3DigitSuffix: '৩-ডিজিট সাফিক্স',
    btnDetails: 'পুরস্কারের বিস্তারিত',
    drawDate: 'ড্র-এর তারিখ',
    amount: 'পুরস্কারের পরিমাণ',
    rank: 'র‍্যাঙ্ক',
    winGreeting: 'অভিনন্দন!',
    loseGreeting: 'পরের বার ভালো ভাগ্য কামনা করি!',
    winAmountMsg: 'আপনি মোট পুরস্কার জিতেছেন',
    noWinMsg: 'এই ড্র-তে আপনার টিকিটের কোনো বিজয়ী কম্বিনেশন মেলেনি।',
    verifyMsg: 'জিএলও সিকিউরিটি লেজার দ্বারা যাচাইকৃত।',
    searchPlaceholder: 'টিকিট, নিবন্ধ, ঘোষণা অনুসন্ধান করুন...',
    searchNoResult: 'কোনো মিল পাওয়া যায়নি।',
    recentSearches: 'সাম্প্রতিক অনুসন্ধান',
    savedTickets: 'আমার সংরক্ষিত টিকিট',
    buyTicketTitle: 'ডিজিটাল লটারি টিকিট ক্রয় করুন',
    chooseDigits: '৬টি সংখ্যা টাইপ বা জেনারেট করুন',
    ticketPrice: 'টিকিট মূল্য: ৮০ ฿',
    paymentMethod: 'পেমেন্ট গেটওয়ে নির্বাচন করুন',
    btnProceedPayment: 'পেমেন্ট সম্পন্ন করুন',
    paymentSuccess: 'পেমেন্ট সফল হয়েছে! টিকিট আপনার ড্যাশবোর্ডে যোগ করা হয়েছে।',
    adminPortal: 'অ্যাডমিন সিএমএস এবং অপারেশনস',
    adminAddResult: 'নতুন ফলাফল আপলোড করুন',
    adminNewsPost: 'নতুন ঘোষণা লিখুন',
    adminDraws: 'সকল লটারি ড্র তালিকা',
    adminTickets: 'ক্রয়কৃত লটারির লগ তালিকা',
    liveCountdown: 'পরবর্তী ড্র এর কাউন্টডাউন'
  }
};

export const MOCK_WINNERS = [
  {
    id: 'w1',
    name: 'Somchai S.',
    amount: '30,000,000 ฿',
    date: '2026-07-01',
    ticket: '123456',
    storyEN: 'A street vendor from Pathum Thani won 5 matching first prize digital tickets!',
    storyTH: 'พ่อค้าแม่ค้าหาบเร่จากปทุมธานี ถูกสลากดิจิทัลรางวัลที่ 1 สะสม 5 ใบ รับเงินจัดเต็ม!',
    storyBN: 'পাথুম থানির একজন সাধারণ হকার ৫টি টিকিট মিলিয়ে ৩০ মিলিয়ন বাথ জিতেছে!'
  },
  {
    id: 'w2',
    name: 'Rahim Khan',
    amount: '6,000,000 ฿',
    date: '2026-06-16',
    ticket: '782390',
    storyEN: 'Expatriate technician matched the first prize through official app purchase.',
    storyTH: 'วิศวกรผู้ทำงานต่างแดนถูกรางวัลใหญ่ด้วยการซื้อออนไลน์ผ่านมือถือครั้งแรก',
    storyBN: 'এক প্রবাসী টেকনিশিয়ান অফিসিয়াল অ্যাপের মাধ্যমে ১ম পুরস্কার জিতেছেন।'
  },
  {
    id: 'w3',
    name: 'Nattaporn P.',
    amount: '12,000,000 ฿',
    date: '2026-06-01',
    ticket: '561902',
    storyEN: 'Teacher from Chiang Mai secured two physical tickets matched perfectly with standard selection.',
    storyTH: 'คุณครูจากเชียงใหม่โชคดีถูกรางวัลที่ 1 จำนวน 2 ใบ รับเงินสมทบทุนครอบครัว',
    storyBN: 'চিয়াং মাই-এর একজন স্কুল শিক্ষক সাধারণ বাছাইয়ে দুটি টিকিট মিলিয়ে কোটিপতি হয়েছেন।'
  }
];
